#!/bin/bash

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

mkdir -p ${dir}/BuildOutput/Bin

dotnet restore

msbuild /property:GenerateFullPaths=true /property:Configuration=Release \
/property:TrimUnusedDependencies=true /t:build /p:OutputPath=${dir}/BuildOutput/Bin



$1
