#!/bin/bash

BUILDER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source ${BUILDER_DIR}/helpers
detectversion

function preclean()
{
    find ${NERVA_DIR}/Src -iname "bin" -o -iname "obj" | xargs rm -rf
}

function postclean()
{
    find ${NERVA_DIR}/Bin -iname "*.pdb" | xargs rm -rf
}

function build()
{
    preclean

    msbuild /t:restore /t:build \
    /p:GenerateFullPaths=true /p:Configuration=Debug /p:TrimUnusedDependencies=true \
    /p:OutputPath=${NERVA_DIR}/Bin/Debug/$1 ${NERVA_DIR}/Src/Nerva.Toolkit.Frontend/Nerva.Toolkit.Frontend.$1.csproj

    postclean
}

build Linux
