#!/bin/bash

BUILDER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NERVA_DIR=$(dirname $BUILDER_DIR)
BUILDER_OUTPUT_DIR=${BUILDER_DIR}/output
source ${BUILDER_DIR}/helpers
detectversion

function install()
{
	mkdir -p ~/.local/bin/nervagui
	cp ./bin/* ~/.local/bin/nervagui
	cp ./nerva-logo-color.png ~/.local/bin/nervagui/nerva-logo-color.png

	#generate a launcher script
	lfile=~/.local/bin/nerva-gui
	echo "#!/bin/bash" > $lfile
	echo "mono $(realpath ~/.local/bin/nervagui)/Nerva.Toolkit.Frontend.exe --log-file $(realpath ~/.nerva)/gui.log --config-file $(realpath ~/.nerva)/gui.config" >> $lfile
	chmod +x $lfile

	dfile=~/.local/share/applications/nerva-gui.desktop

	#Construct .desktop file
	echo "[Desktop Entry]" > $dfile
	echo "Name=Nerva GUI" >> $dfile
	echo "Exec=nerva-gui" >> $dfile
	echo "Terminal=false" >> $dfile
	echo "Type=Application" >> $dfile
	echo "Icon=$(realpath ~/.local/bin/nervagui)/nerva-logo-color.png" >> $dfile

	chmod +x $dfile

	ufile=~/.local/bin/nerva-gui-uninstall

	#Construct uninstaller script
	echo "#!/bin/bash" > $ufile
	echo "rm -rf ~/.local/bin/nervagui" >> $ufile
	echo "rm ~/.local/bin/nerva-gui" >> $ufile
	echo "rm ~/.local/share/applications/nerva-gui.desktop" >> $ufile
	echo "rm ~/.local/bin/nerva-gui-uninstall" >> $ufile

	chmod +x $ufile
}

dir=${BUILDER_OUTPUT_DIR}/Nerva.Toolkit
mkdir -p "${dir}"
cp -r "${BUILDER_OUTPUT_DIR}/bin" ${dir}

cp "${BUILDER_DIR}/nerva-logo-color.png" "${dir}/nerva-logo-color.png"

#Construct linux installer script
lscript=${dir}/install.linux
echo "#!/bin/bash" > $lscript
echo "function $(declare -f install)" >> $lscript
echo "install" >> $lscript
chmod +x $lscript

#windows users aren't getting an installer. That OS just makes it too hard to script something that works

cd ${BUILDER_OUTPUT_DIR}
zip -r ${NERVA_DIR}/nerva-gui-v${NERVA_VERSION}.zip Nerva.Toolkit/