#!/bin/bash

BUILDER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NERVA_DIR=$(dirname $BUILDER_DIR)
BUILDER_OUTPUT_DIR=${BUILDER_DIR}/output
source ${BUILDER_DIR}/helpers
detectversion

macdir="${BUILDER_OUTPUT_DIR}/Nerva.Toolkit.app"
mkdir -p "${macdir}/Contents"
mkdir -p "${macdir}/Contents/MacOS"
mkdir -p "${macdir}/Contents/Resources"

plist=$(sed -e "s/{NERVA_VERSION}/${NERVA_VERSION}/" -e "s/{DISPLAY_NAME}/${NERVA_CODENAME}/" ${BUILDER_DIR}/Info.plist.template)
echo $plist > "${macdir}/Contents/info.plist"

cp "${BUILDER_DIR}/nerva-logo-color.icns" "${macdir}/Contents/Resources/nerva-logo-color.icns"
cp "${BUILDER_OUTPUT_DIR}/bin/Nerva.Toolkit.Frontend.app/Contents/MacOS/Nerva.Toolkit.Frontend" \
	"${macdir}/Contents/MacOS/Nerva.Toolkit.Frontend"

cp -r "${BUILDER_OUTPUT_DIR}/bin/Nerva.Toolkit.Frontend.app/Contents/MonoBundle" "${macdir}/Contents"


cd ${BUILDER_OUTPUT_DIR}
zip -r ${NERVA_DIR}/nerva-gui-v${NERVA_VERSION}_mac.zip Nerva.Toolkit.app/

rm -rf ${BUILDER_OUTPUT_DIR}/bin/Nerva.Toolkit.Frontend.app
